<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  version="1.1"
            xmlns:xs="http://www.w3.org/2001/XMLSchema" 
            xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
            elementFormDefault="qualified" 
            vc:minVersion="1.1" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:annotation>
    <xs:appinfo>ITxPT S02P06 AVMS service - Pattern Monitoring XML Schema Definition Version 2.3.0</xs:appinfo>
    <xs:documentation>ITxPT service interface for standardized interoperability in public transport - XML schema</xs:documentation>
  </xs:annotation>
  <!-- Type definitions -->
  <xs:simpleType name="VersionType">
      <xs:restriction base="xs:string">
        <xs:enumeration value="2.3.0"/>
      </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="MonitoredCallRefType">
    <xs:all>
      <xs:element name="StopPointRef" type="xs:string"/>
      <xs:element minOccurs="0" name="VisitNumber" type="xs:positiveInteger"/>
      <xs:element name="Order" type="xs:positiveInteger"/>
      <xs:element name="VehicleAtStop" type="xs:boolean"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="OnwardCallRefType">
    <xs:all>
      <xs:element name="StopPointRef" type="xs:string"/>
      <xs:element minOccurs="0" name="VisitNumber" type="xs:positiveInteger"/>
      <xs:element name="Order" type="xs:positiveInteger"/>
    </xs:all>
  </xs:complexType>
  <xs:complexType name="OnwardCallsType">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" name="OnwardCallRef" type="OnwardCallRefType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MonitoredPatternType">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="RecordedAtTime" type="xs:dateTime"/>
      <xs:element name="ItemIdentifier" type="xs:string"/>
      <xs:element name="PatternRef" type="xs:string"/>
      <xs:element name="MonitoredCallRef" type="MonitoredCallRefType"/>
      <xs:element minOccurs="0" name="OnwardCalls" type="OnwardCallsType"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="MonitoredPatternNote" type="xs:string"/>
      <xs:element minOccurs="0" name="Extensions" type="xs:anyType"/>
    </xs:choice>
    <!-- Assert conditions to enforce multiplicity and uniqueness constraints -->
    <xs:assert test="count(RecordedAtTime) = 1"/>
    <xs:assert test="count(ItemIdentifier) = 1"/>
    <xs:assert test="count(PatternRef) = 1"/>
    <xs:assert test="count(MonitoredCallRef) = 1"/>
    <xs:assert test="count(OnwardCalls) &lt;= 1"/>
    <xs:assert test="count(Extensions) &lt;= 1"/>
  </xs:complexType>
  <xs:complexType name="MonitoredPatternCancellationType">
    <xs:choice maxOccurs="unbounded">
      <xs:element minOccurs="0" name="RecordedAtTime" type="xs:dateTime"/>
      <xs:element minOccurs="0" name="ItemIdentifier" type="xs:string"/>
      <xs:element minOccurs="0" name="PlannedPatternRef" type="xs:string"/>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Reason" type="xs:string" />
    </xs:choice>
    <!-- Assert conditions to enforce multiplicity and uniqueness constraints -->
    <xs:assert test="count(RecordedAtTime) = 1"/>
    <xs:assert test="count(ItemIdentifier) = 1"/>
    <xs:assert test="count(PlannedPatternRef) = 1"/>
  </xs:complexType>
  <!-- Main element definition -->
  <xs:element name="PatternMonitoringDelivery">
    <xs:complexType>
      <xs:all>
        <xs:element name="MonitoredPattern"  type="MonitoredPatternType"/>
        <xs:element minOccurs="0" name="MonitoredPatternCancellation" type="MonitoredPatternCancellationType"/>
        <xs:element minOccurs="0" name="Extensions" type="xs:anyType"/>
      </xs:all>
      <xs:attribute name="version" use="required" type="VersionType"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
