<?xml version="1.0" encoding="UTF-8"?>
<xs:schema  version="1.1"
            xmlns:xs="http://www.w3.org/2001/XMLSchema" 
            xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
            elementFormDefault="qualified" 
            vc:minVersion="1.1" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:annotation>
    <xs:appinfo>ITxPT S02P04 FMStoIP configuration service - pgninfo operation response XML Schema Definition Version 2.3.0</xs:appinfo>
    <xs:documentation>ITxPT service interface for standardized interoperability in public transport - XML schema</xs:documentation>
  </xs:annotation>
  <!-- Type definitions -->
  <xs:simpleType name="SPNidType">
    <xs:restriction base="xs:positiveInteger">
      <xs:maxInclusive value="9999"/>     
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="PGNHexType">
    <xs:restriction base="xs:token">
      <xs:pattern value="[0-9A-F]{4}"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SPNType"> 
    <xs:all>
      <xs:element name="Name" type="xs:string"/>
      <xs:element name="Unit" type="xs:string"/>
      <xs:element name="DecodeInPGN" type="xs:boolean"/>
    </xs:all>
    <xs:attribute name="id" type="SPNidType" use="required"/>
  </xs:complexType>
  <!-- Main element definition -->
  <xs:element name="PGNDetails">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element name="PGNId" type="PGNHexType"/>
        <xs:element minOccurs="0" name="RepetitionRate" type="xs:positiveInteger"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="SPN" type="SPNType"/>
      </xs:choice>
      <!-- Assert conditions to enforce multiplicity and uniqueness constraints -->
      <xs:assert test="count(PGNId) = 1"/>
      <xs:assert test="count(RepetitionRate) &lt;= 1"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
