#this is a github action file that will test on push and on a schedule
on: 
  push:
  schedule:
    #- cron: '0 * * * *'  # This will run the workflow every hour 
    - cron: '0 0 * * *'  # This will run the workflow every day at midnight
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      - name: Install dependencies
        run: |
          python -m pip install pytest
          python -m pip install mysql-connector-python
          python -m pip install python-dotenv
          python -m pip install pytest gitpython

      #- name: Run tests
      #  run: |
      #    pytest --version
      #    pytest

      - name: Run a multi-line script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
        run: |
          ls -a
          python3 --version
          pytest --version
          pytest
