#this is a github action file that will test on push and on a schedule
on: 
  push:
  schedule:
    #- cron: '0 * * * *'  # This will run the workflow every hour 
    - cron: '0 0 * * *'  # This will run the workflow every day at midnight
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the latest Python 3.x version

      - name: Install dependencies
        run: pip install -r tests/requirements.txt

      - name: Run tests
        env:
          BI_USERNAME: ${{ secrets.BI_USERNAME }}
          BI_PASSWORD: ${{ secrets.BI_PASSWORD }}
          BI_APP_ID: ${{ secrets.BI_APP_ID }}
          BI_APP_DIRECTORY_TENANT_ID: ${{ secrets.BI_APP_DIRECTORY_TENANT_ID }}
          BI_XSD_DATASET_ID: ${{ secrets.BI_XSD_DATASET_ID }}
        run: |
          python3 --version
          pytest --version
          pytest
